// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/10/2025, 11:14:01 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/composables/**/*.{js,ts,mjs}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/utils/**/*.{js,ts,mjs}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Dell/Desktop/Sinh-Ern-Professional_Portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;